# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

find_term_matches <- function(main_term, terms) {
    .Call(`_glex_find_term_matches`, main_term, terms)
}

recurse <- function(x, feature, split, yes, no, quality, lb, ub, cover, U, node, probFunction) {
    .Call(`_glex_recurse`, x, feature, split, yes, no, quality, lb, ub, cover, U, node, probFunction)
}

recurseAlgorithm2 <- function(x, feature, split, yes, no, quality, cover, U, node) {
    .Call(`_glex_recurseAlgorithm2`, x, feature, split, yes, no, quality, cover, U, node)
}

contribute <- function(mat, m_all, S, T, T_subsets, colnum) {
    invisible(.Call(`_glex_contribute`, mat, m_all, S, T, T_subsets, colnum))
}

